//! The committed release-candidate declaration, `.release/release.toml`.
//!
//! This is what a maintainer reviews and merges, and it is the only thing
//! production reads to decide what a release contains. Workflow inputs cannot
//! widen or narrow it: the scope is whatever was reviewed.
//!
//! It deliberately restates versions that are already in the manifests. That
//! duplication is the point -- it is double-entry bookkeeping, and validation
//! rejects a candidate whose declaration and manifests disagree.

use std::{collections::BTreeMap, path::Path};

use anyhow::{Context, Result, bail};
use semver::Version;
use serde::{Deserialize, Serialize};

use crate::{
    config::{Config, Unit},
    workspace::Workspace,
};

pub const SUPPORTED_SCHEMA_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct Candidate {
    pub schema_version: u32,
    /// Units selected for this release, in no particular order; publication
    /// order is derived, not declared.
    pub units: Vec<String>,
    #[serde(flatten)]
    pub declarations: BTreeMap<String, UnitDeclaration>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct UnitDeclaration {
    pub version: Version,
    pub tag: String,
    /// Whether this unit ships as a prerelease. Must agree with the version.
    #[serde(default)]
    pub prerelease: bool,
}

impl Candidate {
    pub fn load(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read release candidate at {}", path.display()))?;
        let candidate: Self = toml::from_str(&text)
            .with_context(|| format!("failed to parse release candidate at {}", path.display()))?;

        if candidate.schema_version != SUPPORTED_SCHEMA_VERSION {
            bail!(
                "release candidate schema version {} is not supported (expected {})",
                candidate.schema_version,
                SUPPORTED_SCHEMA_VERSION
            );
        }
        Ok(candidate)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let text = toml::to_string_pretty(self).context("failed to serialize release candidate")?;
        let header = "# Reviewed release-candidate declaration.\n#\n# Production reads its scope \
                      and versions from this file and nothing else;\n# workflow inputs cannot \
                      widen or narrow it. Generated by `release-tool\n# set-version`, then \
                      reviewed and merged like any other change.\n\n";
        std::fs::write(path, format!("{header}{text}"))
            .with_context(|| format!("failed to write {}", path.display()))?;
        Ok(())
    }

    pub fn declaration(&self, unit: &str) -> Option<&UnitDeclaration> {
        self.declarations.get(unit)
    }
}

/// Render a unit's tag from its configured template.
pub fn render_tag(template: &str, version: &Version) -> String {
    template.replace("{version}", &version.to_string())
}

/// Check a candidate against the workspace and release policy.
///
/// Every problem is collected rather than reported one at a time: a maintainer
/// fixing a candidate wants the whole list.
pub fn validate(ws: &Workspace, config: &Config, candidate: &Candidate) -> Vec<String> {
    let mut problems = Vec::new();

    if candidate.units.is_empty() {
        problems.push("no units selected; a release must contain at least one".to_string());
    }

    for unit in &candidate.units {
        let Some(declaration) = candidate.declaration(unit) else {
            problems.push(format!("unit '{unit}' is selected but has no declaration"));
            continue;
        };

        let Some(unit_config) = config.units.get(unit) else {
            problems.push(format!("unit '{unit}' is not defined in .release/config.toml"));
            continue;
        };

        let expected_tag = render_tag(&unit_config.tag, &declaration.version);
        if declaration.tag != expected_tag {
            problems.push(format!(
                "unit '{unit}' declares tag '{}' but its template yields '{expected_tag}'",
                declaration.tag
            ));
        }

        // A version carrying prerelease identifiers and a `prerelease` flag that
        // says otherwise is exactly the kind of disagreement that would send a
        // prerelease out as `make_latest`.
        let is_prerelease = !declaration.version.pre.is_empty();
        if is_prerelease != declaration.prerelease {
            problems.push(format!(
                "unit '{unit}' declares prerelease = {} but version {} says otherwise",
                declaration.prerelease, declaration.version
            ));
        }

        problems.extend(check_versions_match_manifests(ws, config, unit, declaration));
    }

    for unit in candidate.declarations.keys() {
        if !candidate.units.contains(unit) {
            problems.push(format!(
                "unit '{unit}' is declared but not selected; remove it or add it to `units`"
            ));
        }
    }

    problems
}

/// The declared version must be the version the manifests actually carry.
fn check_versions_match_manifests(
    ws: &Workspace,
    config: &Config,
    unit: &str,
    declaration: &UnitDeclaration,
) -> Vec<String> {
    let unit_kind = match unit {
        "compiler" => Unit::Compiler,
        "sdk" => Unit::Sdk,
        // Templates carry no crates, so there is nothing to cross-check here.
        _ => return Vec::new(),
    };

    let declared = declaration.version.to_string();
    let mut problems = Vec::new();
    for package in config.packages_in(unit_kind) {
        let Some(actual) = ws.packages.get(&package.name) else {
            continue;
        };
        if actual.version != declared {
            problems.push(format!(
                "unit '{unit}' declares version {declared} but '{}' is at {} in its manifest; run \
                 set-version or correct the declaration",
                package.name, actual.version
            ));
        }
    }
    problems
}

#[cfg(test)]
mod tests {
    use super::*;

    fn declaration(version: &str, tag: &str, prerelease: bool) -> UnitDeclaration {
        UnitDeclaration {
            version: Version::parse(version).unwrap(),
            tag: tag.to_string(),
            prerelease,
        }
    }

    #[test]
    fn tags_render_from_their_template() {
        let version = Version::parse("0.10.0").unwrap();
        assert_eq!(render_tag("v{version}", &version), "v0.10.0");
        assert_eq!(render_tag("sdk/v{version}", &version), "sdk/v0.10.0");
    }

    fn config_with_templates() -> Config {
        toml::from_str(
            r#"
schema-version = 1

# The templates unit publishes no crates, so there are no package entries.
packages = []

[units.templates]
tag = "templates/v{version}"
changelog = "tools/cargo-miden/templates/CHANGELOG.md"
"#,
        )
        .unwrap()
    }

    fn empty_workspace() -> Workspace {
        Workspace {
            root: std::path::PathBuf::from("/tmp"),
            packages: Default::default(),
        }
    }

    /// Templates must be releasable as a prerelease. A compiler change that
    /// requires a template change cannot be prereleased otherwise, and §12.5
    /// explicitly allows a template release in the same plan. Stable clients are
    /// protected by resolution selecting the highest *stable* release, not by
    /// forbidding prerelease bundles.
    #[test]
    fn templates_can_be_released_as_a_prerelease() {
        let candidate = Candidate {
            schema_version: 1,
            units: vec!["templates".into()],
            declarations: [(
                "templates".to_string(),
                declaration("2.0.0-rc.1", "templates/v2.0.0-rc.1", true),
            )]
            .into_iter()
            .collect(),
        };

        let problems = validate(&empty_workspace(), &config_with_templates(), &candidate);
        assert!(problems.is_empty(), "{problems:?}");
    }

    #[test]
    fn a_prerelease_flag_must_still_agree_with_the_version() {
        let candidate = Candidate {
            schema_version: 1,
            units: vec!["templates".into()],
            declarations: [(
                "templates".to_string(),
                declaration("2.0.0-rc.1", "templates/v2.0.0-rc.1", false),
            )]
            .into_iter()
            .collect(),
        };

        let problems = validate(&empty_workspace(), &config_with_templates(), &candidate);
        assert_eq!(problems.len(), 1, "{problems:?}");
        assert!(problems[0].contains("says otherwise"), "{}", problems[0]);
    }

    #[test]
    fn candidates_round_trip_through_toml() {
        let candidate = Candidate {
            schema_version: 1,
            units: vec!["compiler".into()],
            declarations: [("compiler".to_string(), declaration("0.10.0", "v0.10.0", false))]
                .into_iter()
                .collect(),
        };

        let dir = std::env::temp_dir().join(format!("candidate-roundtrip-{}", std::process::id()));
        let path = dir.join("release.toml");
        candidate.save(&path).unwrap();
        let loaded = Candidate::load(&path).unwrap();
        assert_eq!(loaded, candidate);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_future_schema_is_refused_rather_than_guessed_at() {
        let dir = std::env::temp_dir().join(format!("candidate-schema-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("release.toml");
        std::fs::write(&path, "schema-version = 99\nunits = []\n").unwrap();

        let err = Candidate::load(&path).unwrap_err().to_string();
        assert!(err.contains("not supported"), "{err}");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
